#!/usr/local/bin/node

// Core deps
const os = require("os");

// Load the (project-specific) configuration file
const config = require("../../config/git-off-my-land-config.js");

// Load the GOML library
const GOML = require("../../node_modules/git-off-my-land/dist/lib/git-off-my-land-lib.js");

// Run the pre-commit hook handler and see what we get!
GOML.runGitHook(config, "pre-commit").then((violations) =>
{
    if(violations)
    {
console.dir(violations);
        
        console.error(config.violationsMessageHeader);

        for(let i in violations)
        {
            const contentViolationsMessage = violations[i].content.join(", ");

            const extensionsViolationsMessage = violations[i].extensions.join(", ");

            const violationsMessage = `Content: ${contentViolationsMessage || "none"}. Filename extension: ${extensionsViolationsMessage || "none"}`;

            console.error(`${i} violates rules - ${violationsMessage}`);
        }

        console.error(config.violationsMessageFooter);

        process.exit(1);
    }
}).catch((err) => 
{
    // TODO: Should we just throw() here? (we're more or less doing that anyway really)
    console.error(`${err}`);
    process.exit(1);
});